### ISSUE TITLE
Can't add/instantiate package with Julia 1.0.3 or 1.1 

### ISSUE THREAD

**Issue by JeffFessler** [vincent-picaud/DirectConvolution.jl#1]
When I add this package then check the status there is a warning:

`Warning: Some packages (indicated with a red arrow) are not downloaded, use `instantiate` to instantiate the current environment`

Running instantiate does not help (no error message, but same status).
I have many other packages installed just fine.  Any idea why this one won't install?

**Comment by chapmanbe** [comment]
I have the same problem with Julia 1.1
