### ISSUE TITLE
can't precompile version 0.2 on julia-1.6.3 with win10 OS

### ISSUE THREAD

**Issue by devel-chm** [vincent-picaud/DirectConvolution.jl#5]
This was the result of attempting to add DirectConvolution to my julia-1.6.3.

> (@v1.6) pkg> activate --temp
>   Activating new environment at `C:\Users\xxx\AppData\Local\Temp\jl_vfU04c\Project.toml`
> 
> (jl_vfU04c) pkg> add DirectConvolution
>    Resolving package versions...
>     Updating `C:\Users\xxx\AppData\Local\Temp\jl_vfU04c\Project.toml`
>   [60a1edcd] + DirectConvolution v0.2.0
>     Updating `C:\Users\xxx\AppData\Local\Temp\jl_vfU04c\Manifest.toml`
>   [60a1edcd] + DirectConvolution v0.2.0
>   [90137ffa] + StaticArrays v0.12.5
>   [2a0f44e3] + Base64
>   [b77e0a4c] + InteractiveUtils
>   [8f399da3] + Libdl
>   [37e2e46d] + LinearAlgebra
>   [56ddb016] + Logging
>   [d6f4376e] + Markdown
>   [9a3f8284] + Random
>   [9e88b42a] + Serialization
>   [2f01184e] + SparseArrays
>   [10745b16] + Statistics
>   [8dfed614] + Test
> Precompiling project...
>   ✗ DirectConvolution
>   0 dependencies successfully precompiled in 2 seconds (1 already precompiled)
>   1 dependency errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the package
>

**Comment by vincent-picaud** [comment]
Sorry for the delay. Unfortunately, I only have access to Linux. 
Please, can you try "import Pkg; Pkg.precompile()" or "using DirectConvolution" and report the error message?

**Comment by devel-chm** [comment]
> julia> using DirectConvolution
[ Info: Precompiling DirectConvolution [60a1edcd-6e1b-57a1-8cb7-ec83bf7a2d9a]
ERROR: LoadError: UndefVarError: LinearFilter not defined
Stacktrace:
 [1] top-level scope
   @ C:\Users\chm\.julia\packages\DirectConvolution\2I0cE\src\DirectConvolution.jl:261
 [2] include
   @ .\Base.jl:386 [inlined]
 [3] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
   @ Base .\loading.jl:1235
 [4] top-level scope
   @ none:1
 [5] eval
   @ .\boot.jl:360 [inlined]
 [6] eval(x::Expr)
   @ Base.MainInclude .\client.jl:446
 [7] top-level scope
   @ none:1
in expression starting at C:\Users\chm\.julia\packages\DirectConvolution\2I0cE\src\DirectConvolution.jl:261
ERROR: Failed to precompile DirectConvolution [60a1edcd-6e1b-57a1-8cb7-ec83bf7a2d9a] to C:\Users\chm\.julia\compiled\v1.6\DirectConvolution\jl_C2B3.tmp.
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:33
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::Base.TTY, internal_stdout::Base.TTY, ignore_loaded_modules::Bool)
   @ Base .\loading.jl:1385
 [3] compilecache(pkg::Base.PkgId, path::String)
   @ Base .\loading.jl:1329
 [4] _require(pkg::Base.PkgId)
   @ Base .\loading.jl:1043
 [5] require(uuidkey::Base.PkgId)
   @ Base .\loading.jl:936
 [6] require(into::Module, mod::Symbol)
   @ Base .\loading.jl:923

**Comment by devel-chm** [comment]
I just tried going back to julia-0.7.0 and got the same error.

**Comment by vincent-picaud** [comment]
Thanks: it seems that the error comes from the fact that " LinearFilter " is not exported. I will check that right now and give you a feedback.

**Comment by vincent-picaud** [comment]
For the moment, under Linux, I cannot reproduce... Sorry.
I will try to understand, but that might take me some time.
In all cases I will inform you here (maybe tomorrow)

**Comment by devel-chm** [comment]
I'm not sure I understand how the module works.  I'm new to Julia since I started learning with 1.0.0 so it may be something that was done differently in earlier julia versions.  I notice that the REQUIRE file lists julia 0.6.

It seems that there are some missing include() or using or import statements in the package.  At least I can't find where the start point for even loading the DirectConvolution module.  There does not appear to be any file DirectConvolution.jl at all.

I hand added a "using StaticArrays" to the linearFilter.jl and was able to run it without error in julia 0.7.0.  Then I added an include("linearFilter.jl") to the top of directConvolution.jl and was able to run that as a script.  I still don't understand how the module loads.

Hope this helps.  Thanks for taking a look.

**Comment by vincent-picaud** [comment]
Thanks for the feedback... I am sorry I do not have access to windows too, because under Linux it seems ok.
Also this was one of my very first Julia package and it would need a serious cleaning (the routines are ok, but that is not good Julia code).
I just pushed v0.2.1 with some small updates. Maybe you can try if this change something.
If not I will do the required work to clean this package, but it will take me some time.

**Comment by devel-chm** [comment]
[wierd_v0.2.0.txt](https://github.com/vincent-picaud/DirectConvolution.jl/files/7550320/wierd_v0.2.0.txt)

I was able to "] dev DirectConvolution" with success.
Precompile works.
All tests pass.

I'm not sure what was up with the v"0.2.0" from before and I'm still unclear of how it was supposed to work.  The changes to v"0.2.1" fixed the package files to resemble what I expected. 

Now I can see a file src/DirectConvolution.jl with the correct capitalization to load.
It is possible that the problem was a corrupted instance in the package server I was using.
It looks good to go and I am looking forward to using your package.

Thanks for the help and apologies for not being able to contribute more.

--Chris

**Comment by vincent-picaud** [comment]
Cool :)
No problem, thank you for your interest in this package.
Best
Vincent
