### ISSUE TITLE
Is Base.filter is being punned by "function filter" in SG_Filter.jl ?

### ISSUE THREAD

**Issue by devel-chm** [vincent-picaud/DirectConvolution.jl#6]
The Base.filter(f,a) takes a function to evaluate, f, and a list/vector/iterator to process, a, and returns the remaining elements from a

The filter() in SG_Filter.jl on the other hand returns the requested filter from the SG filter set and seems more like a getindex().  Almost like the Base.filter() is a verb and filter() in SG_Filter.jl is a noun.

**Comment by vincent-picaud** [comment]
No. It might have been better to call this function "get_filter()". Do you think this is a good idea?

In general, I think the Julia style of using "nouns" for function names (like "size', etc...) is a bad idea. This is not a problem for methods in an OOP language like C++, as we can consider `size` as an attribute, by example:

`size = matrix.size()`

However, in the case of Julia where there are only free functions, I would prefer:

`size = get_size(matrix)`

Unfortunately, this is not the usual Julia convention. Using a noun to name a function, e.g. size, forbids for example writing: 

`size = size(matrix)`

as this causes a name conflict error.

Now I use more and more verbs for my function names (with words separated by '_'), even if it's not Julia style. Unfortunately, "DirectConvolution" is one of my first Julia packages and it has not be written following this convention. 

---------

nb: devel-chm, feel free to use my email ("picaud.vincent dot gmail.com" if you do not get an answer. For a reason I ignore, I do not always receive notifications and I often miss some messages here.
